# Generated by Django 4.2.18 on 2025-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_userbook_delete_note_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='google_book_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
